### ISSUE TITLE
Pruning old records does nothing

### ISSUE THREAD

**Issue by piotrpog** [sjelfull/craft3-audit#46]
I noticed it on version `1.0.4` of plugin and `3.0.32` of craft.
Audit record base grew to 60 mb. When i tried to prune records using control panel button, message about succesfull delete appeared. But no records were removed. When i tried again, it showed "succesfuly removed 0 records".
Uninstalling plugin finally pruned `audit_log` table in database.
I just worry that plugin deleted something else instead of its records :)

**Comment by sjelfull** [comment]
It will never delete anything from other tables besides its own, but this should work.

The records, is any of them older than x days (by default 30 days)?

I'm also planning on adding a max `n` records, so that it will always keep the amount of records below a certain threshold.

**Comment by piotrpog** [comment]
I am at 90% certain that some of these records were older than 30 days. Unfortunetly i am not able to verify this with 100% certainty.

**Comment by sjelfull** [comment]
Let me know if you see this behaviour again.
