### ISSUE TITLE
Changes to Drafts and Globals not tracked

### ISSUE THREAD

**Issue by richcoopa** [sjelfull/craft3-audit#50]
I know this isn't a bug, more of a feature request.

We have a site where a number of "non-admins" make changes to site content using drafts.

Once the content is ready an admin will make these drafts live.
We really need to track the changes that occur in these drafts so we can see who did what.

Another essential is tracking changes to globals - which form quite large parts of our website.

**Comment by sjelfull** [comment]
I actually started on drafts support back when I was working on the initial version, but found the internal API to be very confusing.

I believe they have since made it a bit simpler to work with. Will revisit this as soon as I have some time.

**Comment by richcoopa** [comment]
Many thanks.

**Comment by richcoopa** [comment]
We have decided to purchase the plugin, but would appreciate this is added to your dev list for the coming months. Thanks again.

**Comment by OwenMelbz** [comment]
@sjelfull Hi, would you be able to clarify when support for "Globals" might be coming? We're interested in this plugin but need Globals support before we'll be willing to purchase.

Thanks

**Comment by sjelfull** [comment]
Hi there, i'm tagging 1.1.1 in a sec that adds both draft support (disabled by default, enable in plugin settings by toggling Log Draft Events) and global set tracking.
