### ISSUE TITLE
3.2 Support

### ISSUE THREAD

**Issue by sjelfull** [sjelfull/craft3-audit#53]
With the introduction of 3.2 and Autosave, Audit will list many events while working with an entry.

**Comment by darylknight** [comment]
Related to 3.2; using Craft's Garbage Collection with Audit installed results in an error:

	user-name@webserver:~/apps/user-name$ ./craft gc --delete-all-trashed=1
	Exception 'ParseError' with message 'syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)'

	in /srv/users/user-name/apps/user-name/vendor/superbig/craft-audit/src/Audit.php:59

	Stack trace:
	#0 /srv/users/user-name/apps/user-name/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/srv/users/qepr...')
	#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('superbig\\audit\\...')
	#2 [internal function]: spl_autoload_call('superbig\\audit\\...')
	#3 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/src/services/Plugins.php(870): is_subclass_of('superbig\\audit\\...', 'craft\\base\\Plug...')
	#4 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('audit', Array)
	#5 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/src/base/ApplicationTrait.php(1334): craft\services\Plugins->loadPlugins()
	#6 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
	#7 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
	#8 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
	#9 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
	#10 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
	#11 [internal function]: craft\console\Application->__construct(Array)
	#12 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/di/Container.php(384): ReflectionClass->newInstanceArgs(Array)
	#13 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\console\\A...', Array, Array)
	#14 /srv/users/user-name/apps/user-name/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\console\\A...', Array, Array)
	#15 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
	#16 /srv/users/user-name/apps/user-name/vendor/craftcms/cms/bootstrap/console.php(34): require('/srv/users/qepr...')
	#17 /srv/users/user-name/apps/user-name/craft(21): require('/srv/users/qepr...')
	#18 {main}

**Comment by sjelfull** [comment]
@darylknight Pretty sure that is a PHP version issue (#47).

Probably going to change that to ease the transition for some people.
