### ISSUE TITLE
Deprecation Notice after running composer update

### ISSUE THREAD

**Issue by dejanyy** [sjelfull/craft3-audit#59]
Deprecation Notice: Class superbig\audit\assetbundles\Audit\AuditAsset located in ./vendor/superbig/craft-audit/src/assetbundles/audit/AuditAsset.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by sjelfull** [comment]
Thanks, fixed in 1.1.3.
