### ISSUE TITLE
Logs appear to be saved and displayed in UTC+0

### ISSUE THREAD

**Issue by simple-nicholas** [sjelfull/craft3-audit#66]
I'm working on a site configured to use the GMT+10 (Australia/Melbourne) timezone & the control panel language is en-GB.

The Audit logs appear to be correct otherwise, but they seem to be logged to the DB with a "createdDate" that's 10 hours early.

I tested the rest of the site, and can't find any other issues (like entries being created or saved with the wrong "createdDate").

The issue persists regardless of the user, web browser, even server environment (tried cloning the site to a staging environment & local dev).

**Comment by mildlygeeky** [comment]
Came here to add this as well - everywhere else in Craft lists the user's local time, which makes the audit log pretty confusing.

**Comment by sjelfull** [comment]
Hey, i've found the bug. The date is saved correctly as UTC, but when displayed it doesn't restore it from UTC to a localized date/time.

**Comment by mildlygeeky** [comment]
Thanks for the find @sjelfull! Curious - do you think this plugin will make the move over to Craft 4 at some point?

**Comment by sjelfull** [comment]
@mildlygeeky Yep! Working on it right now, just need some time in-between to get it released. Will have this fix as well. (I realise its been a while) Do you need this fix backported to a version supporting 3.x or are you fine with it being Craft 4 version only?

**Comment by mildlygeeky** [comment]
I'm in full support of leaving the old version behind! :)

**Comment by sjelfull** [comment]
3.0.0 is out with this fix now :)
