### ISSUE TITLE
Using isNew property to check for newly created Element

### ISSUE THREAD

**Issue by sijones-uk** [sjelfull/craft3-audit#67]
### Description

Since Craft 3.7.5, the `isNew` property [is no longer reliable](https://craftcms.com/knowledge-base/upgrading-to-craft-3-7#detecting-newly-saved-entries) when determining whether the entry is being saved for the first time. It is recommended to use the newly created (as of Craft 3.7.5) `firstSave` property instead.

### Steps to reproduce

1. [Line 240 in the `Audit` class](https://github.com/sjelfull/craft-audit/blob/v1/src/Audit.php#L240) uses the `isNew` property to check if the Element is newly created

### Additional info

- Craft CMS version: 3.7.14
- Audit plugin version: 1.1.3
- PHP version: 7.4.1
- Database driver & version: MySQL 5.5.5

**Comment by sjelfull** [comment]
3.0.0 is out with this fix now :)
