### ISSUE TITLE
Craft 4 Support

### ISSUE THREAD

**Issue by brianrivet-tilt** [sjelfull/craft3-audit#69]
Hi,

Is there a plan to have this plugin available for Craft 4?

Thanks!

**Comment by RandomJo** [comment]
@sjelfull Are planning to port this to Craft 4? If not, I'm curious how difficult you think it would be? Would you be able to merge a pull request if we give it a shot?

**Comment by sjelfull** [comment]
@RandomJo 3.0.0 just released with Craft 4 support. PRs are always welcome by the way!
